// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmVBzMZEncRvMKz3dUbdpQMdkzdOGFsLw',
    appId: '1:660463396521:web:66a36115178323281e2bb8',
    messagingSenderId: '660463396521',
    projectId: 'bookswap-d8fe8',
    authDomain: 'bookswap-d8fe8.firebaseapp.com',
    storageBucket: 'bookswap-d8fe8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNVQX1uGnQn7yajt5lNO4GgpgWUEZWUU',
    appId: '1:660463396521:android:6a0081af4b473bd01e2bb8',
    messagingSenderId: '660463396521',
    projectId: 'bookswap-d8fe8',
    storageBucket: 'bookswap-d8fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gS5HPUp44psKm_tYB5Ap_i3BuYydhv4',
    appId: '1:660463396521:ios:e54c0c8d3c287b441e2bb8',
    messagingSenderId: '660463396521',
    projectId: 'bookswap-d8fe8',
    storageBucket: 'bookswap-d8fe8.firebasestorage.app',
    iosClientId: '660463396521-lpf6kitj2lbarubfmk42bs77trqfgios.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gS5HPUp44psKm_tYB5Ap_i3BuYydhv4',
    appId: '1:660463396521:ios:e54c0c8d3c287b441e2bb8',
    messagingSenderId: '660463396521',
    projectId: 'bookswap-d8fe8',
    storageBucket: 'bookswap-d8fe8.firebasestorage.app',
    iosClientId: '660463396521-lpf6kitj2lbarubfmk42bs77trqfgios.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmVBzMZEncRvMKz3dUbdpQMdkzdOGFsLw',
    appId: '1:660463396521:web:31bdb154fae76dd91e2bb8',
    messagingSenderId: '660463396521',
    projectId: 'bookswap-d8fe8',
    authDomain: 'bookswap-d8fe8.firebaseapp.com',
    storageBucket: 'bookswap-d8fe8.firebasestorage.app',
  );
}
